# Site settings é…ç½®ç«™ç‚¹
title: 'å¼€æºäºº'
subTitle: 'ğŸ¤–ä¸€ä¸ªå®‰å“å¼€å‘è€…çš„å°ç«™'
# å¾åä¸ºé•‡,é€¢æ—¶ä¸åˆ©,é€‰é”™æ–‡ç†,å­¦æ–‡å‡ºèº«,å´çˆ±æŠ€æœ¯,ä¸€è·¯è‰°è¾›èµ°è¿‡.ç»ˆè¸å…¥æŠ€æœ¯å¤§é—¨,äºæ­¤åˆ†äº«æˆ‘ä¹‹å¿ƒå¾—,æœ›å‰äººæŒ‡å¯¼,æœ›åäººå€Ÿé‰´.
description: 'ä¸€ä¸ªæ±‡èšäº†å„ç§å®‰å“å¼€æºçš„å°ç«™ï¼Œæ›´å¤šå¼€æºè¯·æœç´¢å…¬ä¼—å·ğŸ‘‰â€œå¼€æºäººâ€'
keyword: 'å¼€æºäºº,å®‰å“,å®‰å“çŸ¥è¯†,è½¯ä»¶,ç ´è§£,ä¸€é”®å…³æ³¨,å…¬ä¼—å·,ç ”å‘,æŠ€æœ¯å®…'
url: 'https://townwang.com' # åœ°å€
image: '//i.loli.net/2018/12/28/5c258b168b588.jpg'

# ä¸éœ€è¦baseurlç•™ç©ºã€‚
baseurl: ''

# css
css:
   font: '//at.alicdn.com/t/font_roc50gemkxpw4s4i.css'
   markdown: '/assets/css/github-markdown.css'
   prism: '/assets/css/prism.css'
   main: '/assets/css/main.css'
   

# å¯¼èˆªæ 
nav:
  å¼€å‘: 'android'
  æ•™ç¨‹: 'tutorial'
  è½¯ä»¶: 'software'
  æ–‡æ¡£: 'document'
  æ„Ÿæ‚Ÿ: 'life'

# å‹æƒ…é“¾æ¥
friends:
  TMaize'Blog: 'http://blog.tmaize.net/'
  å”¯ç¾é™Œé˜¡: "https://hexo.xxrar.com/"
  è“æœç§‘æŠ€ç»„: "http://www.nantz.top"
  mongona: https://www.mongona.com

# Author é…ç½®åšä¸»ä¿¡æ¯
author: 'Town'
nickname: 'Town'
bio: 'Androidå¼€å‘è€…,è½¯ä»¶ç ´è§£,ç¾åŒ–,çˆ±å¥½è€…&æ–‡ç§‘ä¸­çš„æŠ€æœ¯å®…'
avatar: '/assets/img/profile.png'
github: '//github.com/Townwang'
# å¼€å¯æœç´¢
search: true

# å¼€å¯å¤œé—´æ¨¡å¼
nightMode: true

# å¼€å¯åˆ†äº«
social-share: true
social-share-items: ['wechat', 'weibo', 'twitter','linkedin']

#  ä¸»é¢˜çš®è‚¤
theme-color: 'default'  # pink or default

# é…ç½®ç¤¾äº¤ç½‘ç«™url: weibo, zhihu, twitter, instagram, juejin, github, douban, facebook, dribble, uicn, jianshu, medium, linkedin
sns:
  weibo: '//weibo.com/townwang'
  twitter: '//twitter.com/Townwang'
  linkedin: ''

#  è®¾ç½®æ ‡ç­¾
recommend-tags: true #æ˜¾ç¤ºæ¨èæ ‡ç­¾
recommend-condition-size: 12 # è¶…è¿‡12ä¸ªæ˜¾ç¤ºæ¨è

# ç¼–è¯‘è®¾ç½®
paginate: 6
paginate_path: 'page:num'
exclude: ['node_modules','package.json', 'gulpfile.js', '.gitignore', 'README.md']
permalink: /:title

# Markdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
#è®¢é˜…
RSS: true
# Plugins
plugins: [jekyll-paginate]
#ç¼–ç 
encoding: UTF-8
